### ISSUE TITLE
Plugin not working with OJS 3.1.1.4

### ISSUE THREAD

**Issue by CarlosML** [ajnyga/forthcoming#1]
I can enable the plugin from the control panel, but the checkbox "Publish as forthcoming" is missing from the "Schedule for Publication" modal dialog. I'm using the lastest version, as downlodaed from this repository.

**Comment by marlutampus** [comment]
Will you be supporting the latest OJS version anytime soon?

**Comment by ajnyga** [comment]
Hi,

The latest release now supports OJS 3.1.2
