### ISSUE TITLE
No settings to click on

### ISSUE THREAD

**Issue by drfurtado** [ajnyga/forthcoming#14]
> In the plugin settings, choose the Forthcoming issue from the pull-down menu and save settings

There is no `plugin settings` to click. I am on OJS 3.1.2.4. Do you have any ideas why?

Thank you!

https://www.screencast.com/t/rifi4MgttuXQ

**Comment by mhvezina** [comment]
@drfurtado  Are you using the correct version of the plugin? https://github.com/ajnyga/forthcoming/tree/ojs-3-1-2 
"After enabling the plugin the Schedule for Publication form includes a selection "Show as forthcoming". Choose the future issue you wish to publish the article in and check the "show as forthcoming" checkbox, hit save."

**Comment by ajnyga** [comment]
Closing this but thanks to @mhvezina for spotting the problem. The way the plugin works changed considerably when OJS 3.2 with versioning came out and the new instructions apply to that version.
